apiVersion: apps/v1
kind: Deployment

metadata:
  name: gateway-server
  labels:
    app: gateway-server

spec:
  selector:
    matchLabels:
      app: gateway-server

  replicas: 1

  template:
    metadata:
      labels:
        app: gateway-server

    spec:
      initContainers:
        - name: wait-for-infra
          image: busybox
          command: ['sh', '-c', 'until nc -z config-server 8081 && nc -z eureka-server 8761; do echo waiting for infra; sleep 2; done;']

      containers:
      - name: gateway-server
        image: mharko/gateway-server:latest
        imagePullPolicy: Always

        ports:
        - containerPort: 8080

        env:
        - name: URL_CONFIG
          valueFrom:
            configMapKeyRef:
              name: global-config
              key: URL_CONFIG
          
        - name: EUREKA_HOST
          valueFrom:
            configMapKeyRef:
              name: global-config
              key: EUREKA_HOST

        - name: EUREKA_PORT
          valueFrom:
            configMapKeyRef:
              name: global-config
              key: EUREKA_PORT

        resources:
          requests:
            memory: "256Mi"
            cpu: "250m"
          limits:
            memory: "512Mi"

        readinessProbe:
          httpGet: 
            path: /actuator/health
            port: 8080
          initialDelaySeconds: 15
          periodSeconds: 10

---

apiVersion: v1
kind: Service
metadata:
  name: gateway-server  
spec:
  type: NodePort
  selector:
    app: gateway-server
  ports:
  - port: 8080
    targetPort: 8080
    nodePort: 30000
