apiVersion: apps/v1
kind: Deployment

metadata:
  name: inventory-service
  labels:
    app: inventory-service

spec:
  replicas: 1

  strategy:
    type: Recreate

  selector:
    matchLabels:
      app: inventory-service

  template:
    metadata:
      labels:
        app: inventory-service

    spec:
     
      initContainers:
      - name: wait-for-config-server
        image: busybox
        command: ['sh', '-c', 'until nc -z config-server 8081; do echo waiting for config-server; sleep 2; done;']

      containers:
      - name: inventory-service
        image: mharko/inventory-service:latest
        imagePullPolicy: IfNotPresent

        env:
        - name: URL_CONFIG
          valueFrom:
            configMapKeyRef:
              name: global-config
              key: URL_CONFIG
          
        - name: EUREKA_HOST
          valueFrom:
            configMapKeyRef:
              name: global-config
              key: EUREKA_HOST

        - name: EUREKA_PORT
          valueFrom:
            configMapKeyRef:
              name: global-config
              key: EUREKA_PORT

        - name: DB_HOST
          value: "inventory-db"

        - name: DB_PORT
          valueFrom:
            configMapKeyRef:
              name: global-config
              key: DB_PORT

        - name: DB_NAME
          value: "inventory_db"

        - name: DB_USER
          valueFrom:
            configMapKeyRef:
              name: global-config
              key: POSTGRES_USER

        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: db-credentials
              key: POSTGRES_PASSWORD

        - name: KEYCLOAK_URL
          valueFrom:
            configMapKeyRef:
              name: global-config
              key: KEYCLOAK_URL

        - name: KEYCLOAK_REALM
          valueFrom:
            configMapKeyRef:
              name: global-config
              key: KEYCLOAK_REALM

        - name: KEYCLOAK_CLIENT_ID
          valueFrom:
            configMapKeyRef:
              name: global-config
              key: KEYCLOAK_CLIENT_ID

        - name: KEYCLOAK_CLIENT_SECRET
          valueFrom:
            configMapKeyRef:
              name: global-config
              key: KEYCLOAK_CLIENT_SECRET

        - name: MS_AMOUNTS_URL
          valueFrom:
            configMapKeyRef:
              name: global-config
              key: MS_AMOUNTS_URL

        - name: MS_USERS_URL
          valueFrom:
            configMapKeyRef:
              name: global-config
              key: MS_USERS_URL

        - name: MS_KARDEX_URL
          valueFrom:
            configMapKeyRef:
              name: global-config
              key: MS_KARDEX_URL

        - name: IMAGES_PATH
          value: "file:/app/images/"

        volumeMounts:
        - name: images-storage
          mountPath: /app/images

        resources:
          requests:
            memory: "256Mi"
            cpu: "250m"
          limits:
            memory: "512Mi"

      volumes:
      - name: images-storage
        persistentVolumeClaim:
          claimName: images-pvc

---

apiVersion: v1
kind: Service
metadata:
  name: inventory-service
spec:
  type: ClusterIP
  selector:
    app: inventory-service
  ports:
  - port: 80       
    targetPort: 8080 
