apiVersion: apps/v1
kind: Deployment

metadata:
  name: users-service
  labels:
    app: users-service

spec:
  replicas: 1

  strategy:
    type: Recreate

  selector:
    matchLabels:
      app: users-service

  template:
    metadata:
      labels:
        app: users-service

    spec:
          
      initContainers:
      - name: wait-for-config-server
        image: busybox
        command: ['sh', '-c', 'until nc -z config-server 8081; do echo waiting for config-server; sleep 2; done;']

      containers:
      - name: users-service
        image: mharko/users-service:latest
        imagePullPolicy: IfNotPresent

        env:
        - name: URL_CONFIG
          valueFrom:
            configMapKeyRef:
              name: global-config
              key: URL_CONFIG
          
        - name: EUREKA_HOST
          valueFrom:
            configMapKeyRef:
              name: global-config
              key: EUREKA_HOST

        - name: EUREKA_PORT
          valueFrom:
            configMapKeyRef:
              name: global-config
              key: EUREKA_PORT

        - name: DB_HOST
          value: "users-db"

        - name: DB_PORT
          valueFrom:
            configMapKeyRef:
              name: global-config
              key: DB_PORT

        - name: DB_NAME
          value: "users_db"

        - name: DB_USER
          valueFrom:
            configMapKeyRef:
              name: global-config
              key: POSTGRES_USER

        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: db-credentials
              key: POSTGRES_PASSWORD

        - name: KEYCLOAK_URL
          valueFrom:
            configMapKeyRef:
              name: global-config
              key: KEYCLOAK_URL

        - name: KEYCLOAK_REALM
          valueFrom:
            configMapKeyRef:
              name: global-config
              key: KEYCLOAK_REALM

        - name: KEYCLOAK_CLIENT_ID
          valueFrom:
            configMapKeyRef:
              name: global-config
              key: KEYCLOAK_CLIENT_ID

        - name: KEYCLOAK_CLIENT_SECRET
          valueFrom:
            configMapKeyRef:
              name: global-config
              key: KEYCLOAK_CLIENT_SECRET

        - name: MS_CLIENTS_URL
          valueFrom:
            configMapKeyRef:
              name: global-config
              key: MS_CLIENTS_URL

        resources:
          requests:
            memory: "256Mi"
            cpu: "250m"
          limits:
            memory: "512Mi"

---

apiVersion: v1
kind: Service
metadata:
  name: users-service
spec:
  type: ClusterIP
  selector:
    app: users-service
  ports:
  - port: 80       
    targetPort: 8080 
