apiVersion: skaffold/v4beta7
kind: Config
metadata:
  name: toolrent-microservices

build:
  local:
    push: false
  artifacts:
    - image: mharko/eureka-server
      context: Backend/Infrastructure/eureka-service
      jib: {}

    - image: mharko/config-server
      context: Backend/Infrastructure/config-service
      jib: {}

    - image: mharko/gateway-server
      context: Backend/Infrastructure/gateway-service
      jib: {}

    - image: mharko/amounts-service
      context: Backend/Microservices/amounts
      jib: {}

    - image: mharko/clients-service
      context: Backend/Microservices/clients
      jib: {}

    - image: mharko/inventory-service
      context: Backend/Microservices/inventory
      jib: {}

    - image: mharko/kardex-service
      context: Backend/Microservices/kardex
      jib: {}

    - image: mharko/loans-service
      context: Backend/Microservices/loans
      jib: {}

    - image: mharko/reports-service
      context: Backend/Microservices/reports
      jib: {}

    - image: mharko/users-service
      context: Backend/Microservices/users
      jib: {}

    - image: local-mharko/frontend
      context: Frontend/my-app
      docker:
        dockerfile: Dockerfile

manifests:
  rawYaml:
    - Backend/Kubernetes-Config/Global/*.yaml
    - Backend/Kubernetes-Config/DB/*.yaml
    - Backend/Kubernetes-Config/Infrastructure/*.yaml
    - Backend/Kubernetes-Config/Microservices/*.yaml
    - Frontend/Kubernetes-Config/*.yaml

deploy:
  kubectl: {}

profiles:
  - name: production
    build:
      local:
        push: true
    manifests:
      rawYaml:
        - Backend/Kubernetes-Config-Prod/Global/*.yaml
        - Backend/Kubernetes-Config-Prod/DB/*.yaml
        - Backend/Kubernetes-Config-Prod/Infrastructure/*.yaml
        - Backend/Kubernetes-Config-Prod/Microservices/*.yaml
        - Frontend/Kubernetes-Config-Prod/*.yaml