apiVersion: skaffold/v4beta7
kind: Config
metadata:
  name: toolrent-microservices

build:
  artifacts:
    - image: mharko/eureka-server
      context: Backend/Infrastructure/eureka-service
      jib:
        project: .

    - image: mharko/config-server
      context: Backend/Infrastructure/config-service
      jib:
        project: .

    - image: mharko/gateway-server
      context: Backend/Infrastructure/gateway-service
      jib:
        project: .

    - image: mharko/amounts-service
      context: Backend/Microservices/amounts
      jib:
        project: .

    - image: mharko/clients-service
      context: Backend/Microservices/clients
      jib:
        project: .

    - image: mharko/inventory-service
      context: Backend/Microservices/inventory
      jib:
        project: .

    - image: mharko/kardex-service
      context: Backend/Microservices/kardex
      jib:
        project: .

    - image: mharko/loans-service
      context: Backend/Microservices/loans
      jib:
        project: .

    - image: mharko/reports-service
      context: Backend/Microservices/reports
      jib:
        project: .

    - image: mharko/users-service
      context: Backend/Microservices/users
      jib:
        project: .

manifests:
  rawYaml:
    - Backend/Kubernetes-Config/Global/*.yaml
    - Backend/Kubernetes-Config/DB/*.yaml
    - Backend/Kubernetes-Config/Infrastructure/*.yaml
    - Backend/Kubernetes-Config/Microservices/*.yaml

deploy:
  kubectl: {}

portForward:
  - resourceType: service
    resourceName: gateway-server
    port: 8080
    localPort: 8080
  
  - resourceType: service
    resourceName: eureka-server
    port: 8761
    localPort: 8761
    
  - resourceType: service
    resourceName: keycloak-service
    port: 9090
    localPort: 31000