---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: db-credentials
  namespace: default
spec:
  encryptedData:
    POSTGRES_PASSWORD: AgCYv/d7qTfIGvTqsNn2acYoVCaL87Iz+3eHBijcRdH9nJ08iZEegW4WO2TYEtXYH0qoKOaQnNGZkquEm1XfDh8ve5fY7HQUr7QZ/zgcibj3mx30XEQV3W7KgfPJEiKYfhuefpqRXpQAb/c6Scjjy7m3fKa4dRVex34c5U/rLr5WtGnXIp7f9/bLbfxdpZRHZ5LlM+ZBzCV6FoPrG/1S+UEf/taU6uyyjcTln8d27mqVlw2AfvceUKlOFRfwM7WzmVOWlOnL2TRQbV1L190QbJAlvWRx042qcsd4j0+aWoqhS7J6Xq/qMoJ6i7IiYc5q+bU2dre/FWOSi6N1zGBPnijSysBH9Kg0JA0BNtXN25WHBJVElUVJZjlE9MaLUdjNsXLDVi+vaNeLi+Dz7zGuYRBmSoHMJdT4z4ihLMhyPXKQ+aIcI+hvEtyGMWNULoBeiZB6UUrAS6wEt3Rlc9fUaxpoMqVJcctCW2lO/CA/qRYh63/r38lRW+HIlaB6pgWXBFCI75n+EJ9OKptasEq9A8Ef7966Haj91H3lqYZTcOdrLEHYehIXen2NTuaeuykqqZ8d3I5wKP2lJY26lsaIAeYbPHUtxgnZJReTEKjyPKySmHIl+YMFaWMHUnj2jEKNBLYuGQrwH8bJuY00sVbOcpTHqejCFPXEU6Jhxjhpjzgtu4S9c3ZTdxyka6D2mTH3+nZdyrGY
  template:
    metadata:
      name: db-credentials
      namespace: default
