---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: db-credentials
  namespace: default
spec:
  encryptedData:
    POSTGRES_PASSWORD: AgBd7w4efCV60zFJSkVjC9dF850+rg5Awi8oRIdnzBBwSSBy5XGkIqjA3PxvBXRH7wX1fUXMLgOwAcKdzpApolg3n5WiikvJ/8Z8e79DA5x4rfmCZOc9TWAqfMIEcioKKT1xnQmtfpLDoVAjwMOXU2cvjqxkI1E3s/OoGIb4TvdjEc7ipE7M03e+Y9lP/Z2Lvloib2msN0cbnmsO7DBBdjD41jnWA4xyDmQhisp7AID0jOxrBPe5a56yoyein1azGtQetIix3YdnwT+CWk75y7XH9FgodCrWA/PXshEuyUOfufQ1m0DF1bWrI3kvQOOfZWPh6RAfnvR/R+JxBhSo39C3by3//sxHVDtUWOGvISPI2hmJt6hhsSBGDUD8e3GipwHjwGcAR3hpaEWH+3xwPPQ2ayw6DUU3xVTLgKythDLmYyO4FUbqjzdzYHGG3wiC+KKJEAvh4owOLLUsIYLGnxuTJJPe/u06QAAhARadK2SWKPfBe/Xxj+9eFhAi2SMuxRn80lmgAnl5QXkmKD5HbqDoC2pz1nnX4gs4qXk+GqqkcL0EvPMM36OnPJb0SNQIgs40qlKHVNyt3virGGRodA6an/rX6LBGa90h+m1mlVt6Luzt6Fd69+wcrvYXGvUQ/nVYNAYj6IJwNt0dKemNNaf5zXJ90NsW0CFe9WgKRJq/iTOIlY1LNFeukvhk7KLg3XzJGrYr
  template:
    metadata:
      name: db-credentials
      namespace: default
