---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: db-credentials
  namespace: default
spec:
  encryptedData:
    foo: AgCFNEU7IhcLQDUOSgnwkGu/debod7yxSbE+UZbEoysB5Mmc+8B9rVRJhle4zbcI4xc/tlqa8XJgfTt1GYkMHMb7yENy3KsjUSrSygVX2hLCDarSjSVzEBc35WXhxaw+UL3xXaONuRahbDBebcEp2VsqW6HKDlJguzkniwDFfVw979wkxulyj33M0mrnOTPpnHYt55kA634XrUnI5YNFbAolLz/WanxmpkryYnB8acFHzHamAaxI8dIoBVuoQ3X1652AEtYmj85O+VorJCHLbM9ZMNeCzpijrF7wsvfNEerus+FssayNoE7W+DTbp5rHJ8g9XMPJtn1MK1ETFJCblQG0nU0b51QxMLDGTPkXZTbAazHgvzoF3qFGEpTqi8fl5Nzq0c10WkHKlKQr84v5kRljnTWDLRZRCb0jPkyZSB2OX+PaeQVo5+ETRAO+oL8esJBqlH5//wZfx2ttFR2C80KbaUykyn1GytdmdwCl/TSntO3HyquwbLr4LeNMsOeQZy08PvWgIe/YkeDQTWOEBFSjiHMwb05Of/YQTvEiUHEHWPVWsBTAJzkx+o7caZ96y599UonTAlIwEtWe+cVKUval4OPRUrRBt/eEx6IUH0OahueDvJrheaWv/DpVpRTfW1B+FLwYkXFoyoJQlqOZgRqwr9bpw1TiLYkYFOcG2jmUP/WBhYW7AJTnMc4ktzTNxmBn5wg6
  template:
    metadata:
      name: db-credentials
      namespace: default
