apiVersion: apps/v1
kind: Deployment

metadata:
  name: eureka-server
  labels:
    app: eureka-server

spec:
  selector:
    matchLabels:
      app: eureka-server

  replicas: 1

  template:
    metadata:
      labels:
        app: eureka-server

    spec:
      containers:
      - name: eureka-server
        image: mharko/eureka-server:latest
        imagePullPolicy: IfNotPresent

        ports:
        - containerPort: 8761

        resources:
          requests:
            memory: "256Mi"
            cpu: "250m"
          limits:
            memory: "512Mi"

        readinessProbe:
          httpGet:
            path: /actuator/health
            port: 8761
          initialDelaySeconds: 8
          periodSeconds: 10

---

apiVersion: v1
kind: Service
metadata:
  name: eureka-server
spec:
  type: ClusterIP
  selector:
    app: eureka-server
  ports:
  - port: 8761
    targetPort: 8761