---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: db-credentials
  namespace: default
spec:
  encryptedData:
    POSTGRES_PASSWORD: AgAyS66GUHnHlP0QOb9tS7dPMC5cQwMrNKVmQK0DcthHi0wLAVG0ZOzxsWm2LcD7oxQcPp4awq63eNBpxTZ+9iU4tUsRibK3sLk8n0CkivLzpez6Jqu0RPbCC5cswPN0aaBJtr5tOTadKlnyaCVhTCx7DL3NIjSIKLMk4X5anPiEEbTSHSn+2SkkIZ0Rh3S7/OgBA0KQ8Xnm9CUTDNS5wqEptRnT+qYJg/zjOWtsx8XG7dCT164gi1DPkBG6zSsN63yoMNDqcDABu5VlISTJ1qHfjT2KJfdfrfVdwSZPplOfw4ZWwSuec1gsXTKrf81pLTipV1MOk2l/0WXKpysMSK96JENleBZYzEiXY3P4dI0rdXBYZ+pwwaYMqTbdPkabXq7FQZIlN3k/ABvbCdF98tSh+o3LvCF8Ob3dTFCbO4E9hVry9MH6V1uuwzWw0VL3X5tToCuS24JOzU6dnaaLxN7YL7TUOKZS/MCpjuWalv2iYxCI6C8Y55iPARC9hzX2TTXLDQZYTmtk3f2S7lNDFgDHD4NRf5PliUqTA9+t+JZpHQ8ykYPbGkahLk/ETeQwP71GQru8Vjvshk4Hi99k971spJmXr/g8O7h9zKf9Bb5tDYEm7feoS+sUyDCPb8tb9+esniXaX5Uy7NtuZleezH3YjDiHewvXZeFSyLZ2K8xMplXFYQUQHYnQiuN2YfK4xg/q8JhA
  template:
    metadata:
      name: db-credentials
      namespace: default
