---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: db-credentials
  namespace: default
spec:
  encryptedData:
    POSTGRES_PASSWORD: AgAH5vbhxyOOXsAW27hmmf1cYFx19igdxoA5vpXd0jV7mU0NndVfvb+loIj6/STgJqSkAeFEXmr2G1uW38uPx0GMEa+xtoeyVKdANE0ufU13dLJAPawPIymDF4Ya0uqgD5IeDScSCIQsaKdnT57XVQWsTcnBJA/pO2Bck0dXQSzybDq1die9NGg3MZTgMzl/GUqc7lB0E7BEME8X7xutvnsC2flrfPlt8XsQ7mAGsOSClczGFYqLNKl2tvgLdIilNgVnolAHgqw7SPvge+HSk53k1ewX39YAnww/VXROiZLSrDmQdBuPHpc6ganGhzXlZ3B15Pf1StBGKOEgXkR/qOMAT9xxovwjovVemSJu1k5nYnkaLQ7ZM6laq7llOV5uTfhGLH9cJaFPm+PjkJYx99Pi8KHLQxkSX27UX0KdpgQ/qgGhbla3zYlYQMdLrQnUtcn5/pCnObPukKZ4xg7trjn89b+Q5GIMEcXuG9O7gdziQMCvM/Bv8zK/QKy+GJEYbQr0cVq9o7xeDJuuN/xC5IsLm+0aBv8gpObTjcHLa9PGdMvLZUEdJK3qmj6C+2xJycUshVCKC4L+iMpQJLSgo1nXh7cdC6Yx3FPFdI8Tqo3DxQBJ69p6uq7tzx0qOLSNFB2gZ3gQz3ieI08KiNAHz4ujF/M2TPE7ijYVcjQCe0GMlm9HkgjxAPqobzaTEUnWsbagW4Xa
  template:
    metadata:
      name: db-credentials
      namespace: default
