---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: db-credentials
  namespace: default
spec:
  encryptedData:
    password: AgBDhCVDW31890n9tEJDMTCPFlepF55KpdqLKBWq7kqGnOTyEKFIpng3gkYV1gV+Tqj6klKVtBGPNPCSFtTkgn+NQ2+qjH+ogZuOWrTKRhgRaaBX/LKqoKPiATDcx4T0gTC+OrofEKn4R/tUzyseagPnh/Q2Z/7628dqW7dP+TIGOZOCSbwpnFjl1sgoI7wodZbwwa9tQTwSq6uzj80gbe5S9ReN7BTE26ECkO3B3OmBzPBn/KD8gSgzFHWjbhzUNKZ1jAzuPNA8Y1Mvvl4F0k652D009Fn0C0rMfAgQbKuu7fNh0mObZkw3DjB1zoSUNjOlJvvViI9t/n87kQnbtE21mf4CgkNGCmT7zK7DAe4zaqyHIUOUo0kB1w5umLc4XPsi4NSGqPrOAz+1wRhyMRv1UXNooHPRXCc1eQo7edMVvR8thXq58dTbdTtBRHccjv5VwgROyxyhxuTAGUEANfBGKq9OXdffVR7l9on3UPqn4tQY29gIZFJwBfVPj2xNVTm1M3H7YBSRl411OLsZcofItmishV3onJGynCfdwryFHBwngdtJajmlO6Hns6HdHF4yLE5h1FMFhHQzCVeuJLG9rlcwSSTd/6njCYmwhtE2OsHRec+N3M0/8/VheQuVRvJkY5gTE2pQ/dSdPGMFLXjA15zj77HNTEROSkxGNhlc50v5MzeggvhY7DrKORdgNRcztUiZ
  template:
    metadata:
      name: db-credentials
      namespace: default
